export const productDetailActionTypes = {
    GET_PRODUCT_DETAIL_START: 'GET_PRODUCT_DETAIL_START',
    GET_PRODUCT_DETAIL_SUCCESS: 'GET_PRODUCT_DETAIL_SUCCESS',
    GET_PRODUCT_DETAIL_FAILURE: 'GET_PRODUCT_DETAIL_FAILURE'
}