export const productsActionTypes = {
    GET_PRODUCTS_HIGHLIGHT_START: 'GET_PRODUCTS_HIGHLIGHT_START',
    GET_PRODUCTS_HIGHLIGHT_SUCCESS: 'GET_PRODUCTS_HIGHLIGHT_SUCCESS',
    GET_PRODUCTS_HIGHLIGHT_FAILURE: 'GET_PRODUCTS_HIGHLIGHT_FAILURE',
    GET_SHOP_PRODUCTS_START: 'GET_SHOP_PRODUCTS_START',
    GET_SHOP_PRODUCTS_SUCCESS: 'GET_SHOP_PRODUCTS_SUCCESS',
    GET_SHOP_PRODUCTS_FAILURE: 'GET_SHOP_PRODUCTS_FAILURE'
}