export const purchaseItemActionTypes = {
    GET_PURCHASE_ITEM_START: 'GET_PURCHASE_ITEM_START',
    GET_PURCHASE_ITEM_SUCCESS: 'GET_PURCHASE_ITEM_SUCCESS',
    GET_PURCHASE_ITEM_FAILURE: 'GET_PURCHASE_ITEM_FAILURE',
    SET_PRICE: 'SET_PRICE',
    INCREMENT_ITEM_QUANTITY: 'INCREMENT_ITEM_QUANTITY',
    DECREMENT_ITEM_QUANTITY: 'DECREMENT_ITEM_QUANTITY'
}